### ISSUE TITLE
git workflow

### ISSUE THREAD

**Issue by noobjey** [noobjey/sales_engine#1]
This is the git workflow that was suggested by Mike and Horace using GitHub + Waffe.io

**Comment by adamcaron** [comment]
1. add issue in Waffle.io
2. create feature branch
3. do some code
4. push branch
5. submit pull request, with description that "closes 'issue#'" (ie. "closes #1")
6. other person reviews pull request
7. (if merged) git checkout master
8. git pull origin master
9. merge master into branch

**Comment by adamcaron** [comment]
To Delete Branch (local & remote)

local
git branch -D <branch_name>

remote
git push origin :<branch_name>
