### ISSUE TITLE
'Invoice' Complete: 'Relationships' and 'Listing & Searching'

### ISSUE THREAD

**Issue by noobjey** [noobjey/sales_engine#28]

**Comment by adamcaron** [comment]
http://tutorials.jumpstartlab.com/projects/sales_engine.html

**Comment by adamcaron** [comment]
# Relationships
- `transactions` returns a collection of associated `Transaction` instances
- `invoice_items` returns a collection of associated `InvoiceItem` instances
- `items` returns a collection of associated `Items` by way of `InvoiceItem` objects
- `customer` returns an instance of `Customer` associated with this object
- `merchant` returns an instance of `Merchant` associated with this object

**Comment by adamcaron** [comment]
http://tutorials.jumpstartlab.com/projects/sales_engine.html

# Listing and Searching Collections

For repository class you need to offer:
- `all` returns all instances
- `random` returns a random instance
- `find_by_X(match)`, where `X` is some attribute, returns a single instance whose `X` attribute case-insensitive attribute matches the `match` parameter. For instance, `customer_repository.find_by_first_name("Mary")` could find a `Customer` with the first name attribute `"Mary"` or `"mary"` but not `"Mary Ellen"`.
- `find_all_by_X(match)` works just like `find_by_X` except it returns a collection of all matches. If there is no match, it returns an empty Array.
